name: pr_dotnet

on:
  push:
    paths:
      - "framework/dotnet/**"
      - "samples/dotnet/**"
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: MegaLinter 
        uses: oxsecurity/megalinter/flavors/dotnet@v6.12.0
        env:
          IGNORE_GITIGNORED_FILES: true
          PRINT_ALL_FILES: true
          REPORT_OUTPUT_FOLDER: ${GITHUB_WORKSPACE}/megalinter-reports
          DISABLE: SPELL,COPYPASTE,YAML
          DISABLE_LINTERS: MARKDOWN_MARKDOWN_TABLE_FORMATTER,REPOSITORY_CHECKOV,REPOSITORY_TRIVY,REPOSITORY_SECRETLINT
          # FILTER_REGEX_EXCLUDE: BenchPress/|engine/|examples/|\.github/workflows|\.devcontainer|\.editorconfig|\.gitmodules
          FILTER_REGEX_EXCLUDE: '(BenchPress/|engine/|examples/|\.github/workflows|\.devcontainer|\.editorconfig|\.gitmodules|\*.sln|\*.md)'
          # FILTER_REGEX_EXCLUDE: (BenchPress/|engine/|examples/|\.github/workflows|\.devcontainer|\.editorconfig|\.gitmodules)
          # FILTER_REGEX_EXCLUDE: /BenchPress|/engine|/examples|\.github/workflows|\.devcontainer|\.editorconfig|\.gitmodules
          # FILTER_REGEX_EXCLUDE: |
          #   BenchPress/
          #   engine/
          #   examples/
          #   \.github/workflows
          #   \.devcontainer
          #   \.editorconfig
          #   \.gitmodules

          VBDOTNET_FILTER_REGEX_INCLUDE: '(framework/dotnet|samples/dotnet)'