name: pr_python

on:
  push:
    paths:
      - "framework/python/**"
      - "samples/python/**"
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: MegaLinter 
        uses: oxsecurity/megalinter/flavors/python@v6.12.0
        env:
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true
          PRINT_ALL_FILES: true
          DISABLE: SPELL,COPYPASTE,YAML
          DISABLE_LINTERS: MARKDOWN_MARKDOWN_TABLE_FORMATTER,PYTHON_MYPY
          FILTER_REGEX_EXCLUDE: '(BenchPress/|engine/|examples/|\.github/workflows|\.devcontainer|\.editorconfig|\.gitmodules|/framework/dotnet|samples/dotnet|\.sln|\.md|LICENSE)'
          FILTER_REGEX_INCLUDE: '(framework/python|samples/python)'
          REPORT_OUTPUT_FOLDER: ${GITHUB_WORKSPACE}/megalinter-reports